SIM_KuaiVideo_x2_001_f03d7f2a:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_002_5269f78d:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_003_5a0527d5:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_004_a1ddb518:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_005_8727b056:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_006_748595d3:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_007_1494367e:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
SIM_KuaiVideo_x2_008_f03d7f2a:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    verbose: 1
