SDIM_Ebnerd_small_x1_000:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_001:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_002:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_003:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_004:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_005:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_006:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_007:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_Ebnerd_small_x1_008:
    accumulation_steps: 1
    attention_dim: 256
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 4096
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 8
    item_info_fields: 3
    l2_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 1000
    metrics: [gAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 16
    num_heads: 8
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
